# Use root/example as user/password credentials
version: "3.4"
services:
  # Vue Frontend
  cena-frontend:
    container_name: cena-frontend
    image: cena-frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - 9920:24678
    environment:
      - GLOBAL_MIDDLEWARE=null
      - BASE_URL=""
      - ALLOW_SIGNUP=true
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  # Fast API
  cena-api:
    container_name: cena-api
    image: cena-api:dev
    build:
      context: ./
      target: development
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9921:9000
    environment:
      TZ: America/Anchorage # Specify Correct Timezone for Date/Time to line up correctly.
    volumes:
      - ./dev/data:/app/dev/data
      - ./cena:/app/cena

  # Mkdocs
  cena-docs:
    container_name: cena-docs
    image: squidfunk/mkdocs-material
    restart: always
    ports:
      - 9922:8000
    volumes:
      - ./docs:/docs
