# Use root/example as user/password credentials
version: "3.1"
services:
  # Vue Frontend
  mealie-frontend:
    container_name: dev-mealie-frontend
    image: mealie-frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 9920:3000
    environment:
      - API_URL=http://dev-mealie-api:80
      - BASE_URL=""
      - ALLOW_SIGNUP=true
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  # Fast API
  mealie-api:
    container_name: dev-mealie-api
    image: mealie-api:dev
    build:
      context: ./
      target: development
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9921:9000
    environment:
      TZ: America/Anchorage # Specify Correct Timezone for Date/Time to line up correctly.
    volumes:
      - ./dev/data:/app/dev/data
      - ./mealie:/app/mealie
